"""empty message

Revision ID: 11fc2b70777b
Revises: ac48acd0a01b
Create Date: 2022-05-13 13:21:04.175875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fc2b70777b'
down_revision = 'ac48acd0a01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.String(length=255), nullable=True))
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###
