"""empty message

Revision ID: 302df9dd1189
Revises: e0dd063dd652
Create Date: 2022-05-15 09:39:24.963035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302df9dd1189'
down_revision = 'e0dd063dd652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###
