"""empty message

Revision ID: be28ddb959b4
Revises: d7519c019782
Create Date: 2022-05-15 11:39:16.783890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be28ddb959b4'
down_revision = 'd7519c019782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'blogs', ['blog_id'], ['id'])
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'blog_id')
    # ### end Alembic commands ###
