"""empty message

Revision ID: d913bfbc1e50
Revises: cabba036e1e9
Create Date: 2022-05-16 00:51:59.180729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd913bfbc1e50'
down_revision = 'cabba036e1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'updated')
    # ### end Alembic commands ###
